// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB4I7zQeoF9mDk6ZwZuri9lAlHyP0RUX4',
    appId: '1:109106935558:web:d60cc7c5a76eca96c09087',
    messagingSenderId: '109106935558',
    projectId: 'automate-2491e',
    authDomain: 'automate-2491e.firebaseapp.com',
    storageBucket: 'automate-2491e.firebasestorage.app',
    measurementId: 'G-KQM7K24C57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkS9hx5C5VSkAM-9rRaWEorv8fyQFsHFw',
    appId: '1:109106935558:android:9ea8aae8066cd820c09087',
    messagingSenderId: '109106935558',
    projectId: 'automate-2491e',
    storageBucket: 'automate-2491e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE_Wc87QbCmuB7xKhkpSAr8OvBYSGrx18',
    appId: '1:109106935558:ios:9046656edcf3f2a6c09087',
    messagingSenderId: '109106935558',
    projectId: 'automate-2491e',
    storageBucket: 'automate-2491e.firebasestorage.app',
    iosBundleId: 'com.example.automate12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE_Wc87QbCmuB7xKhkpSAr8OvBYSGrx18',
    appId: '1:109106935558:ios:9046656edcf3f2a6c09087',
    messagingSenderId: '109106935558',
    projectId: 'automate-2491e',
    storageBucket: 'automate-2491e.firebasestorage.app',
    iosBundleId: 'com.example.automate12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB4I7zQeoF9mDk6ZwZuri9lAlHyP0RUX4',
    appId: '1:109106935558:web:90577456f269a199c09087',
    messagingSenderId: '109106935558',
    projectId: 'automate-2491e',
    authDomain: 'automate-2491e.firebaseapp.com',
    storageBucket: 'automate-2491e.firebasestorage.app',
    measurementId: 'G-FXPX56P8J4',
  );
}
